Flowpack/Flowpack.ElasticSearch

composer.json
The curl PHP extension is used and thus this change marks it as required
in the composer manifest.
=> [TASK] Require ext-curl in composer manifest

Classes/Flowpack/ElasticSearch/Indexer/Aspect/IndexerAspect.php, Classes/Flowpack/ElasticSearch/Package.php, Configuration/Settings.yaml
Also removes the second default Elasticsearch host.
=> [TASK] Use realtimeIndexing.enabled from TYPO3CR.Search settings

Configuration/Settings.yaml
Because of the unkeyed array (using "-"), Flow will merge the array of
setting TYPO3.Flow.persistence.doctrine.eventListeners with another
unkeyed array from another package which will cause issue that the last
package's setting will override the previous ones.
=> [BUGFIX] Assign array key to doctrine event listener

Classes/Flowpack/ElasticSearch/Indexer/Object/ObjectIndexer.php
This bugfix removes the handledObjects checking from ObjectIndexer. After "[TASK] Don't keep the full object in handledObjects property", which was neccessary to reduce the memory usage when indexing huge amount of objects, the handledObjects checking prevents indexing. 
This happens, because the method spl_object_hash is used to generate a unique identifier. As the documentation states "This id can be used as a hash key for storing objects, or for identifying an object, as long as the object is not destroyed", but in fact, this is exactly what we wanted to achieve: Destroy the objects after indexing.
Otherwise it would be possible to use the PersistanceManager to get the unique identifier, but this would prevent non persistent objects from being indexed in ElasticSearch. I think this may …
=> [Bugfix] Remove checking of HandledObjects

Classes/Flowpack/ElasticSearch/Domain/Model/Client/ClientConfiguration.php, Classes/Flowpack/ElasticSearch/Transfer/RequestService.php, Configuration/Settings.yaml, Documentation/Index.rst
This change adds the two new client settings options "username" and
"password" which allows for setting credentials being integrated into
the request URL when accessing Elasticsearch instances protected by
HTTP Basic Auth.
=> [FEATURE] Support username / password for SaaS Elasticsearch

Classes/Flowpack/ElasticSearch/Transfer/RequestService.php, Documentation/Index.rst
This change makes the RequestService more resilient for some cases when
the HTTP Request sent to Elasticsearch did not contain the username
and password anymore, even though it has been configured in the
settings.
While the root cause is the Http\Request::create() method in Flow,
this change at least provides a workaround which allows for connecting
with Elasticsearch instances protected with HTTP Basic Auth.
Also circumvents a rare case where the content of a PUT request contains
"null" as a string.
=> [BUGFIX] Request drops username / password in some cases

Classes/Flowpack/ElasticSearch/Transfer/Exception.php, Classes/Flowpack/ElasticSearch/Transfer/Response.php, Tests/Functional/Fixtures/TweetRepository.php
If a request to elasticsearch fails, for example in case of a
missing request, the error part of the ES response array is set
as the exception message which is then tried to be rendered
as part of the message and raises an exception due to array
string conversion.
=> [BUGFIX] Fix exception rendering on failed request

Classes/Flowpack/ElasticSearch/Domain/Model/Index.php
This allow to skip the index name from the ElasticSearch request
URI. This is usefull for some parts of the API, like the Scroll API.
=> TASK: Allow to skip the index name from the URI

Classes/Flowpack/ElasticSearch/Package.php
Since the boot step that was used no longer exists for a while the
realtime indexing via signals was never initalized and didn't work.
This change uses an existing boot step identifier to bind the
signals so that using them has the desired effect.
=> BUGFIX: Signal based indexing is triggered again

Classes/Flowpack/ElasticSearch/Transfer/RequestService.php
This change allow to call ElasticSearch with get arguments:
$this->getIndex()->request('GET', '/_search/scroll?scroll=1m');
This is required because some ElasticSearch API argument are only
available as GET request arguments.
=> BUGFIX: Support get arguments in API request

Classes/Flowpack/ElasticSearch/Command/IndexCommandController.php, Classes/Flowpack/ElasticSearch/Command/MappingCommandController.php, Classes/Flowpack/ElasticSearch/Domain/Exception/DocumentPropertiesMismatchException.php, Classes/Flowpack/ElasticSearch/Domain/Factory/ClientFactory.php, Classes/Flowpack/ElasticSearch/Domain/Model/AbstractType.php, Classes/Flowpack/ElasticSearch/Domain/Model/Client.php, Classes/Flowpack/ElasticSearch/Domain/Model/Client/ClientConfiguration.php, Classes/Flowpack/ElasticSearch/Domain/Model/Document.php, Classes/Flowpack/ElasticSearch/Domain/Model/GenericType.php, Classes/Flowpack/ElasticSearch/Domain/Model/Index.php, Classes/Flowpack/ElasticSearch/Domain/Model/Mapping.php, Classes/Flowpack/ElasticSearch/Indexer/Object/IndexInformer.php, Classes/Flowpack/ElasticSearch/Indexer/Object/ObjectIndexer.php, Classes/Flowpack/ElasticSearch/Indexer/Object/Transform/DateTransformer.php, Classes/Flowpack/ElasticSearch/Indexer/Object/Transform/TransformerFactory.php, Classes/Flowpack/ElasticSearch/Mapping/BackendMappingBuilder.php, Classes/Flowpack/ElasticSearch/Mapping/EntityMappingBuilder.php, Classes/Flowpack/ElasticSearch/Mapping/MappingCollection.php, Classes/Flowpack/ElasticSearch/Package.php, Classes/Flowpack/ElasticSearch/Transfer/Exception.php, Classes/Flowpack/ElasticSearch/Transfer/RequestService.php, Classes/Flowpack/ElasticSearch/Transfer/Response.php, LICENSE, Tests/Functional/Domain/AbstractTest.php, Tests/Functional/Domain/DocumentTest.php, Tests/Functional/Fixtures/Tweet.php, Tests/Functional/Indexer/Object/IndexInformerTest.php, Tests/Functional/Indexer/Object/ObjectIndexerTest.php, Tests/Functional/Mapping/MappingBuilderTest.php, composer.json
This does some code style cleanup, fixes type hints and adjusts the code in two places:
- indexing skips non-gettable properties now
- no longer use deprecated `getClassNameByObject`
The latter makes this package depend on Flow 3.0 or higher.
Also, the package now contains a LICENSE file (MIT license).
=> TASK: Clean up code and tests

composer.json
There is one deprecated method call being used, but it works fine.
=> TASK: Mark as compatible with Flow 3.x

Documentation/Indexer.rst
This replaces tabs with spaces and clears up the way analysis settings
need to be indented.
=> TASK: Tweak indentation of examples in Indexer.rst

Classes/Transfer/Exception.php
The `Flowpack\ElasticSearch\Transfer\Exception` fails
with a conflict when it tries to use Response from
flow while there is another Response class in the
same namespace. Fixed by renaming the imported
Response Object.
=> BUGFIX: Use named Flow response

README.md
The package is actually working with Elasticseach 2.x, contrary to
what the README said.
=> TASK: Fix supported Elasticsearch versions in README

Classes/Annotations/Mapping.php
In order to enable fielddata in the mapping-annotations the class Flowpack\ElasticSearch\Annotations\Mapping should have a property 'fielddata' (boolean).
=> FEATURE: Property fielddata in Annotations/Mapping

Classes/Annotations/Mapping.php
This is a much needed property to be able to index a "toOne" relation as "object" and specify properties of that relation to be indexed.
This all works perfectly well with a Custom Transformer but it is currently not possible to configure the mapping right. This simple change would change that.
See:
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/properties.html
=> Added "properties" property to mapping annotation

Classes/Domain/Model/AbstractType.php
Newser versions of Elasticsearch do not return `found` in the DELETE-Action. Meanwhile the result is in `result`. 
Here are two examples:
**2.x**:
```
{
"_shards" : {
"total" : 10,
"failed" : 0,
"successful" : 10
},
"found" : true,
"_index" : "twitter",
"_type" : "tweet",
"_id" : "1",
"_version" : 2
}
```
**6.x**:
```
{
"_shards" : {
"total" : 2,
"failed" : 0,
"successful" : 2
},
"_index" : "twitter",
"_type" : "tweet",
"_id" : "1",
"_version" : 2,
"_primary_term": 1,
"_seq_no": 5,
"result": "deleted"
}
```
=> BUGFIX: Adapted delete check for new version (since 6.x)

Classes/Domain/Model/Index.php
For ES 5 it can be a problem to have double slash in the url, which is mentioned here: https://discuss.elastic.co/t/getting-500-error-in-es5-0-0/65146/2
I stumbled upon this problem, after fixing an issue in DocumentDriver for the ContentRepositoryAdapter:
```
Elasticsearch request failed. [POST http://elasticsearch:9201//_search/scroll]: Array ( [root_cause] => Array ( [0] => Array ( [type] => string_index_out_of_bounds_exception [reason] => String index out of range: 0 ) ) [type] => string_index_out_of_bounds_exception [reason] => String index out of range: 0 ) ; Response body: {"error":{"root_cause":[{"type":"string_index_out_of_bounds_exception","reason":"String index out of range: 0"}],"type":"string_index_out_of_bounds_exception","reason":"String index out of range: …
```
=> BUGFIX: ltrim request path when index name is not used

Classes/Domain/Factory/DocumentFactory.php, Classes/Domain/Model/AbstractType.php, Classes/Domain/Model/Document.php, Classes/Indexer/Object/ObjectIndexer.php, README.md
I changed the code to support Elasticsearch version 7 for custom domain model indexing. 
It will then no longer work with elasticsearch 5 because the API changed from ES version 5 to 6 why I introduced these changes:
- `\Flowpack\ElasticSearch\Domain\Model\AbstractType::findDocumentById` will use the path "_doc" to find documents
- `\Flowpack\ElasticSearch\Domain\Model\Document::store` will use the path "_doc" store documents to the index
=> TASK: Modify to work with Elasticsearch 7

Configuration/Settings.yaml
This makes the option more visible and follows our guidelines for
"settings documentation"
=> TASK: Add http scheme default to settings

Classes/Domain/Factory/DocumentFactory.php
This removes the warning
`PHP Deprecated:  Required parameter $response follows optional parameter $id in Application/Flowpack.ElasticSearch/Classes/Domain/Factory/DocumentFactory.php on line 40`
=> BUGFIX: Fix deprecation warning with PHP 8

Classes/Transfer/RequestService.php, Configuration/Settings.yaml
Sometimes it's necessary to control SSL verification if you have a cluster running in a local infrastructure with self signed certificates
=> TASK: add settings to control transport ssl checks if necessary

Classes/Domain/Model/Index.php
With this feature any configured index can get a prefix in ElasticSearch, making it possible to
have several contexts indexed into different indexes in the same elastic instance.
At the same time index settings are kept centralised and used by the "base" index name.
=> FEATURE: Allow configuring a prefix for the index name via Settings

Classes/Domain/Model/Index.php, Classes/Service/DynamicIndexSettingService.php, Configuration/Testing/Settings.yaml, Tests/Functional/Domain/AbstractTest.php, Tests/Functional/Domain/IndexTest.php
Due to the order of operations with injectSettings and object injection it could cause errors to resolve the index settings early enough to override the name property.
This is now resolved later. Additionally via `Index::getOriginalName()` one can now obtain the name without prefix, if necessary.
Testing overhauled with custom bundle as defined in Readme.
Additionally fixed the filtering of settings on `update` which was not working correctly (anymore?)
Fixes: #103
=> BUGFIX: Setting injection doesn't cause errors

Classes/Domain/Model/Document.php, Tests/Functional/Domain/DocumentTest.php
Simple fix noticed during tests. Maybe a breaking version with cleanup at some point is in order.
=> BUGFIX: Return values can be null, tests should work

Classes/Domain/Model/Mapping.php
The parameter was previously deprecated and removed in elasticsearch 8
=> TASK: Remove include_type_name default parameter

Classes/Domain/Model/Client/ClientConfiguration.php
Fixes the issue https://github.com/Flowpack/Flowpack.ElasticSearch/issues/115 by allowing to set the `username` and `password` to null. If both values are null, the `Authorization` header is not applied to the ElasticSearch request.
https://github.com/Flowpack/Flowpack.ElasticSearch/issues/115
=> TASK: remove Authorization header if username and password are null
